safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "Lanskask"
description: "Полка для хранения моих мыслишек и заметок."
url: "https://lanskask.github.io"
baseurl: "/WoodTractBlog" # baseurl: "https://lanskask.github.io/WoodTractBlog"
# site.github.url: 
# twitter_username: your-name
github_username:  Lanskask # (your name)
accent: "#f7f7e6" # accent color for blog column

author: "WoodTractor"
email: "grey.wooden.tractor@gmail.com"

# google analytics tracking code, please change the value
# g_analytics: ""

# language settings
# isolang:ru
paginate: 5

# exclude files
gems:
  - jekyll-feed
  - jekyll-paginate
  # - i18n_filter
exclude:
  - LICENSE
  - README.md
